#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 20 and: 

H=0

while [ $H -le 12 ]
do
	echo "Hour: $H"
	M=1
	while [ $M -le 59 ]
	do
		echo "$M"
		M=$(( M+1 ))
	done
	H=$(( H+1 ))
done
